class2use = {...
    'unknown'...
    'blurry'...
    'marSnow'...
    'phaeIndiv'...
    'phaeMany'...
    'phaeMany23'...
    'squashed'...
    'whiteout'...
    'ribbon'...
    'copepod'...
    'ctenophore'...
    };
    
    save class2use_vpr class2use