class2use = {...
    'unknown'...
    'blurry'...
    'marSnow'...
    'phaeIndiv'...
    'phaeMany'...
    'phaeMany2_v8'...
    'Chaetoceros protuberans'...
    'squashed'...
    'whiteout'...
    };
    
    save class2use_vpr class2use