
function createfigure(X1, Y1, X2, Y2, X3, Y3,X4,Y4)
close all;
load ('\\raspberry\d_work\IFCB1\ifcb_data_mvco_jun06\Manual_fromClass\summary\count_manual_04Oct2013_day.mat')
load Tall_day2006_2013.mat
ind59 = find(~isnan(ml_analyzed_mat_bin(:,59)));
ind14 = find(~isnan(ml_analyzed_mat_bin(:,14)));
ind_high59 = find(classcount_bin(:,59)>0);

%TO make cirlces around any that have >10%
ind_highpercent = find((((classcount_bin(:,59)./ml_analyzed_mat_bin(:,59)))./...
((classcount_bin(:,59)./ml_analyzed_mat_bin(:,59))+(classcount_bin(:,14)./ml_analyzed_mat_bin(:,14))))>.1);

%To make circles around >10% and more than 5 counts of Guinardia
%ind_highpercent = find((((classcount_bin(:,59)./ml_analyzed_mat_bin(:,59)))./...
%((classcount_bin(:,59)./ml_analyzed_mat_bin(:,59))+(classcount_bin(:,14)./ml_analyzed_mat_bin(:,14))))>.1...
%& (classcount_bin(:,14)./ml_analyzed_mat_bin(:,14))>5);




%CREATEFIGURE(X1,Y1,X2,Y2)
  X1 = matdate_bin(ind59);
  Y1 = classcount_bin(ind59,59)./ml_analyzed_mat_bin(ind59,59);
  X2 = matdate_bin(ind14);
  Y2 = classcount_bin(ind14,14)./ml_analyzed_mat_bin(ind14,14);
  X3 = matdate_bin(ind_highpercent);
  Y3 = classcount_bin(ind_highpercent, 14)./ml_analyzed_mat_bin(ind_highpercent,14);
  X4 = matdate_bin(ind_high59);
  Y4 = classcount_bin(ind_high59, 59)./ml_analyzed_mat_bin(ind_high59, 59);

%  Auto-generated by MATLAB on 17-Jul-2013 10:39:53

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'YTickLabel',{'0', '10', '20', '30', '40', '50'},...
    'YTick',[0 10 20 30 40 50],...
    'XTickLabel',{'Sept 1','Sept 15', 'Oct 1', 'Oct 15'},...
    'XTick',[734017  734031 734047 734061],...
    'XGrid','off',...
    'FontSize',14,...
    'CLim',[0 1]);
% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[734017 734078]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 50]);
box(axes1,'on');
hold(axes1,'all');



plot(X2,Y2,'Marker','.','LineWidth',2,'Color',[0 0 1], 'MarkerSize',14);
% Create plot
plot(X1,Y1,'Marker','d','LineWidth',2,'MarkerEdgeColor',[1 0 0],...
                       'MarkerFaceColor',[1 1 1],'Color',[1 0 0], 'MarkerSize',6);

plot(X3,Y3,'Marker','o','LineStyle','none','LineWidth',2,'Color', [1 0 0], 'MarkerSize',8);

plot(X4,Y4,'Marker','d','LineStyle','none','MarkerEdgeColor',[1 0 0],...
                       'MarkerFaceColor',[1 0 0],'Color',[1 0 0], 'MarkerSize',6);
% Create plot

set(gcf, 'position', [0 700 700 300]);

%for i = [734017  734031 734047 734061];
 %   line([i,i], [0 50],'LineWidth',1, 'Color',[0 0 0]);
%end



% Create xlabel
%xlabel('Date (2009)','FontSize',14);

% Create ylabel
ylabel('Chains (mL-1)','FontSize',14);

legend('G. delicatula', 'infected G. delicatula', '>10 % infection');

title('2009 Type 1');


%*****************************
figure2 = figure;

% Create axes
axes1 = axes('Parent',figure2,...
    'YTickLabel',{'0', '10', '20', '30'},...
    'YTick',[0 10 20 30],...
    'XTickLabel',{'June 1','June 15', 'July 1', 'July 15'},...
    'XTick',[734655  734669 734685 734699],...
    'XGrid','off',...
    'FontSize',14,...
    'CLim',[0 1]);
% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[734655 734699]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 30]);
box(axes1,'on');
hold(axes1,'all');



plot(X2,Y2,'Marker','.','LineWidth',1,'Color',[0 0 1]);
% Create plot
plot(X1,Y1,'Marker','d','LineWidth',1,'MarkerEdgeColor',[1 0 0],...
                       'MarkerFaceColor',[1 1 1],'Color',[1 0 0], 'MarkerSize',4);

plot(X3,Y3,'Marker','o','LineStyle','none','Color', [1 0 0], 'MarkerSize',6);

plot(X4,Y4,'Marker','.','LineStyle','none','LineWidth',1, 'Color',[1 0 0]);
% Create plot

set(gcf, 'position', [0 350 700 300]);

%for i = [734017  734031 734047 734061];
 %   line([i,i], [0 50],'LineWidth',1, 'Color',[0 0 0]);
%end



% Create xlabel
%xlabel('Date (2009)','FontSize',14);

% Create ylabel
ylabel('Chains (mL-1)','FontSize',14);

legend('G. delicatula', 'infected G. delicatula', '>10 % infection');

title('2011 Type 1');

%*****************************
figure3 = figure;

% Create axes
axes1 = axes('Parent',figure3,...
    'YTickLabel',{'0', '10', '20', '30', '40', '50', '60'},...
    'YTick',[0 10 20 30 40 50 60],...
    'XTickLabel',{'Dec 1', 'Jan 1', 'Feb 1', 'Mar 1', 'Apr 1', 'May 1'},...
    'XTick',[733012 733043 733074 733102  733133 733163],...
    'XGrid','off',...
    'FontSize',14,...
    'CLim',[0 1]);
% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[733012 733163]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 60]);
box(axes1,'on');
hold(axes1,'all');



plot(X2,Y2,'Marker','.','LineWidth',1,'Color',[0 0 1]);
% Create plot
plot(X1,Y1,'Marker','d','LineWidth',1,'MarkerEdgeColor',[1 0 0],...
                       'MarkerFaceColor',[1 1 1],'Color',[1 0 0], 'MarkerSize',4);

plot(X3,Y3,'Marker','o','LineStyle','none','Color', [1 0 0], 'MarkerSize',6);

plot(X4,Y4,'Marker','.','LineStyle','none','LineWidth',1, 'Color',[1 0 0]);
% Create plot

set(gcf, 'position', [700 700 700 300]);

%for i = [734017  734031 734047 734061];
 %   line([i,i], [0 50],'LineWidth',1, 'Color',[0 0 0]);
%end



% Create xlabel
%xlabel('Date (2009)','FontSize',14);

% Create ylabel
ylabel('Chains (mL-1)','FontSize',14);

legend('G. delicatula', 'infected G. delicatula', '>10 % infection');

title('2007 Type 2');

figure4 = figure;

% Create axes
axes1 = axes('Parent',figure4,...
    'YTickLabel',{'0', '10', '20', '30', '40', '50', '60'},...
    'YTick',[0 10 20 30 40 50 60],...
    'XTickLabel',{'Dec 1', 'Jan 1', 'Feb 1', 'Mar 1', 'Apr 1', 'May 1'},...
    'XTick',[733743 733774 733805 733833  733864 733894],...
    'XGrid','off',...
    'FontSize',14,...
    'CLim',[0 1]);
% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[733743 733894]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 60]);
box(axes1,'on');
hold(axes1,'all');



plot(X2,Y2,'Marker','.','LineWidth',1,'Color',[0 0 1]);
% Create plot
plot(X1,Y1,'Marker','d','LineWidth',1,'MarkerEdgeColor',[1 0 0],...
                       'MarkerFaceColor',[1 1 1],'Color',[1 0 0], 'MarkerSize',4);

plot(X3,Y3,'Marker','o','LineStyle','none','Color', [1 0 0], 'MarkerSize',6);

plot(X4,Y4,'Marker','.','LineStyle','none','LineWidth',1, 'Color',[1 0 0]);
% Create plot

set(gcf, 'position', [700 350 700 300]);

%for i = [734017  734031 734047 734061];
 %   line([i,i], [0 50],'LineWidth',1, 'Color',[0 0 0]);
%end



% Create xlabel
%xlabel('Date (2009)','FontSize',14);

% Create ylabel
ylabel('Chains (mL-1)','FontSize',14);

legend('G. delicatula', 'infected G. delicatula', '>10 % infection');

title('2009 Type 2');

%************************

figure5 = figure;

% Create axes
axes1 = axes('Parent',figure5,...
    'YTickLabel',{'0', '10', '20', '30', '40', '50', '60'},...
    'YTick',[0 10 20 30 40 50 60],...
    'XTickLabel',{'Dec 1', 'Jan 1', 'Feb 1', 'Mar 1', 'Apr 1', 'May 1'},...
    'XTick',[734838 734869 734900 734929  734960 734990],...
    'XGrid','off',...
    'FontSize',14,...
    'CLim',[0 1]);
% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[734838 734990]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 60]);
box(axes1,'on');
hold(axes1,'all');



plot(X2,Y2,'Marker','.','LineWidth',1,'Color',[0 0 1]);
% Create plot
plot(X1,Y1,'Marker','d','LineWidth',1,'MarkerEdgeColor',[1 0 0],...
                       'MarkerFaceColor',[1 1 1],'Color',[1 0 0], 'MarkerSize',4);

plot(X3,Y3,'Marker','o','LineStyle','none','Color', [1 0 0], 'MarkerSize',6);

plot(X4,Y4,'Marker','.','LineStyle','none','LineWidth',1, 'Color',[1 0 0]);
% Create plot

set(gcf, 'position', [700 0 700 300]);

%for i = [734017  734031 734047 734061];
 %   line([i,i], [0 50],'LineWidth',1, 'Color',[0 0 0]);
%end



% Create xlabel
%xlabel('Date (2009)','FontSize',14);

% Create ylabel
ylabel('Chains (mL-1)','FontSize',14);

legend('G. delicatula', 'infected G. delicatula', '>10 % infection');

title('2012 Type 2');

%**********************
figure6 = figure;

% Create axes
axes1 = axes('Parent',figure6,...
    'YTickLabel',{'0', '10', '20', '30'},...
    'YTick',[0 10 20 30],...
    'XTickLabel',{'Nov 15', 'Dec 1', 'Dec 15'},...
    'XTick',[734822 734838 734852],...
    'XGrid','off',...
    'FontSize',14,...
    'CLim',[0 1]);
% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[734822 734852]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 30]);
box(axes1,'on');
hold(axes1,'all');



plot(X2,Y2,'Marker','.','LineWidth',1,'Color',[0 0 1]);
% Create plot
plot(X1,Y1,'Marker','d','LineWidth',1,'MarkerEdgeColor',[1 0 0],...
                       'MarkerFaceColor',[1 1 1],'Color',[1 0 0], 'MarkerSize',4);

plot(X3,Y3,'Marker','o','LineStyle','none','Color', [1 0 0], 'MarkerSize',6);

plot(X4,Y4,'Marker','.','LineStyle','none','LineWidth',1, 'Color',[1 0 0]);
% Create plot

set(gcf, 'position', [0 0 700 300]);

%for i = [734017  734031 734047 734061];
 %   line([i,i], [0 50],'LineWidth',1, 'Color',[0 0 0]);
%end



% Create xlabel
%xlabel('Date (2009)','FontSize',14);

% Create ylabel
ylabel('Chains (mL-1)','FontSize',14);

legend('G. delicatula', 'infected G. delicatula', '>10 % infection');

title('2011 Type 1 - again');
%***************************************************



figure7 = figure;

% Create axes
axes1 = axes('Parent',figure7,...
    'YTickLabel',{'0', '5', '10'},...
    'YTick',[0 5 10],...
    'XTickLabel',{'Oct 15', 'Nov 1', 'Nov 15'},...
    'XTick',[733330 733347 733361],...
    'XGrid','off',...
    'FontSize',14,...
    'CLim',[0 1]);
% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[733330 733361]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 10]);
box(axes1,'on');
hold(axes1,'all');



plot(X2,Y2,'Marker','.','LineWidth',1,'Color',[0 0 1]);
% Create plot
plot(X1,Y1,'Marker','d','LineWidth',1,'MarkerEdgeColor',[1 0 0],...
                       'MarkerFaceColor',[1 1 1],'Color',[1 0 0], 'MarkerSize',4);

plot(X3,Y3,'Marker','o','LineStyle','none','Color', [1 0 0], 'MarkerSize',6);

plot(X4,Y4,'Marker','.','LineStyle','none','LineWidth',1, 'Color',[1 0 0]);
% Create plot

set(gcf, 'position', [1300 700 400 300]);

%for i = [734017  734031 734047 734061];
 %   line([i,i], [0 50],'LineWidth',1, 'Color',[0 0 0]);
%end



% Create xlabel
%xlabel('Date (2009)','FontSize',14);

% Create ylabel
ylabel('Chains (mL-1)','FontSize',14);

%legend('G. delicatula', 'infected G. delicatula', '>10 % infection');

title('2008 Type 3');

%*******************
figure8 = figure;

% Create axes
axes1 = axes('Parent',figure8,...
    'YTickLabel',{'0', '5', '10'},...
    'YTick',[0 5 10],...
    'XTickLabel',{'Jun 1' 'Jun 15', 'Jul 1', 'Jul 15'},...
    'XTick',[734290 734304 734320 734334],...
    'XGrid','off',...
    'FontSize',14,...
    'CLim',[0 1]);
% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[734290 734334]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 10]);
box(axes1,'on');
hold(axes1,'all');



plot(X2,Y2,'Marker','.','LineWidth',1,'Color',[0 0 1]);
% Create plot
plot(X1,Y1,'Marker','d','LineWidth',1,'MarkerEdgeColor',[1 0 0],...
                       'MarkerFaceColor',[1 1 1],'Color',[1 0 0], 'MarkerSize',4);

plot(X3,Y3,'Marker','o','LineStyle','none','Color', [1 0 0], 'MarkerSize',6);

plot(X4,Y4,'Marker','.','LineStyle','none','LineWidth',1, 'Color',[1 0 0]);
% Create plot

set(gcf, 'position', [1300 350 400 300]);

%for i = [734017  734031 734047 734061];
 %   line([i,i], [0 50],'LineWidth',1, 'Color',[0 0 0]);
%end



% Create xlabel
%xlabel('Date (2009)','FontSize',14);

% Create ylabel
ylabel('Chains (mL-1)','FontSize',14);

%legend('G. delicatula', 'infected G. delicatula', '>10 % infection');

title('2010 Type 3');