%Autogenerated and edited by EP October 2018
%use:
%To concatenate time, latitude and longitude columns from files labeled such from the armstrong:
%ARXXMMDD_0000.csv
%Put all files in one directory without other CSV's
%Write the directory name below under metadata_loc

clear all; close all;
metadata_loc = '\\sosiknas1\IFCB_data\NESLTER_transect\metadata\AR31_Oct2018\';
filelist = dir([metadata_loc, '*00.csv']);
Date = [];
Time = [];
lat =[];
lon = [];

for i = 1:length(filelist);
   filename =  [metadata_loc, char(filelist(i).name)];
    
    
%filename = '\\sosiknas1\IFCB_data\NESLTER_transect\metadata\AR24_October2017\AR171023_0000.csv';
delimiter = ',';
startRow = 3;

% Format string for each line of text:
%   column1: text (%s)
%	column2: text (%s)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%f%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

% Open the text file.
fileID = fopen(filename,'r');

% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

% Close the text file.
fclose(fileID);

% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

% Allocate imported array to column variable names
DATE_GMT = dataArray{:, 1};
TIME_GMT = dataArray{:, 2};
Dec_LAT = dataArray{:, 3};
Dec_LON = dataArray{:, 4};

Date = [Date; DATE_GMT];
Time = [Time; TIME_GMT];
lat = [lat;Dec_LAT];
lon = [lon; Dec_LON];


% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;
end

temp = char(Date(1:end));
temp2= char(Time(1:end));
temp2= temp2(:,1:9);
%temp = char(Date([2:21232 21234:46442 46444:end]));%special case for bad
%data in second elg file of GGMAy2016 data.
%temp2= char(Time([2:21232 21234:46442 46444:end]));

[year month day] = datevec(temp);
[a b c hour minute second] = datevec(temp2);

date = datenum(year, month, day, hour, minute, second);

cruise_start = datevec(date(1))
cruise_end = datevec(date(end))

latitude = lat;
longitude = lon;
matlab_date = date;
%save \\sosiknas1\IFCB_data\NESLTER_transect\metadata\AR31_Oct2018\metadata_raw matlab_date latitude longitude hour minute second day month year;
