function createfigure(X1, Y1, X2, Y2, X3, Y3,X4,Y4)
load ('\\raspberry\d_work\IFCB1\ifcb_data_mvco_jun06\Manual_fromClass\summary\count_manual_current_day.mat')
load('\\raspberry\d_work\IFCB1\ifcb_data_mvco_jun06\Manual_fromClass\summary\IFCB_carbon_manual_14Feb2015') %from summary_size_classes.m

%datelim = [datenum({'6-1-2006', '9-10-2013'})];
datelim = [datenum({'6-1-2006', '3-1-2015'})];

Tnode = load('\\SOSIKNAS1\Lab_data\MVCO\EnvironmentalData\Tall_day');
Tbeam = load('Tday_beam');

Tday = Tnode.Tday; 
mdate = Tnode.mdate;
%Tday = Tbeam.Tday_beam;
%mdate = Tbeam.mdate_mat;

colsize = size(classcount_bin,2);
gapsize = 30;
ii = find(diff(matdate_bin) > gapsize);
while ~isempty(ii),
    ii = ii(1);
    matdate_bin = [matdate_bin(1:ii); NaN; matdate_bin(ii+1:end)];
    classcount_bin = [classcount_bin(1:ii,:); repmat(NaN, 1,colsize); classcount_bin(ii+1:end,:)];
    ml_analyzed_mat_bin = [ml_analyzed_mat_bin(1:ii,:); repmat(NaN, 1,colsize); ml_analyzed_mat_bin(ii+1:end,:)];
    ii = find(diff(matdate_bin) > gapsize);
end;

[ ind_Gdel, class_label ] = get_G_delicatula_ind( class2use, class2use );

ind_main = strmatch('Guinardia_delicatula', class2use);
ind_parasite = strmatch('G_delicatula_parasite', class2use);
ind_extparas = strmatch('G_delicatula_external_parasite', class2use);


indp2use = find(~isnan(ml_analyzed_mat_bin(:,ind_parasite)) | nansum(ml_analyzed_mat_bin,2) == 0);
indG2use = find(~isnan(ml_analyzed_mat_bin(:,ind_main)) | nansum(ml_analyzed_mat_bin,2) == 0);
indp_high = find(classcount_bin(:,ind_parasite)>0);

%ind60 = find(~isnan(ml_analyzed_mat_bin(:,ind_extparas)) | nansum(ml_analyzed_mat_bin,2) == 0);

ind_highpercent = find((((classcount_bin(:,ind_parasite)./ml_analyzed_mat_bin(:,ind_parasite)))./...
((classcount_bin(:,ind_parasite)./ml_analyzed_mat_bin(:,ind_parasite))+(classcount_bin(:,ind_main)./ml_analyzed_mat_bin(:,ind_main))+(classcount_bin(:,ind_extparas)./ml_analyzed_mat_bin(:,ind_extparas))))>.1);


%To make circles around >10% and more than 5 counts of Guinardia
%ind_highpercent = find((((classcount_bin(:,ind_parasite)./ml_analyzed_mat_bin(:,ind_parasite)))./...
%((classcount_bin(:,ind_parasite)./ml_analyzed_mat_bin(:,ind_parasite))+(classcount_bin(:,ind_main)./ml_analyzed_mat_bin(:,ind_main))))>.1...
%& (classcount_bin(:,ind_main)./ml_analyzed_mat_bin(:,ind_main))>5);

lowT = find((Tday < 4));
gray = .93;


%****************added for new panel***************

[ ind_Gdel, class_label ] = get_G_delicatula_ind( classes, classes );

Y = C10_20phyto_mat(:)+C20_infphyto_mat(:);  %total > 10 microns
[ mdate_mat, y_mat, yearlist, yd ] = timeseries2ydmat( Cmdate_day, sum(C_day_mat(:,ind_Gdel),2) ); %total G. del
ii = find(~isnan(Y));

X = Cmdate_mat(ii);
Y = y_mat(ii)./Y(ii);

gapsize = 30;
ii = find(diff(X) > gapsize);
while ~isempty(ii),
    ii = ii(1);
    X = [X(1:ii); NaN; X(ii+1:end)];
    Y = [Y(1:ii); NaN; Y(ii+1:end)];
    ii = find(diff(X) > gapsize);
end;

%******end of added for new panel********************


%CREATEFIGURE(X1,Y1,X2,Y2)
  X1 = matdate_bin(indp2use);
  Y1 = classcount_bin(indp2use,ind_parasite)./ml_analyzed_mat_bin(indp2use,ind_parasite);
  X2 = matdate_bin(indG2use);
  Y2 = classcount_bin(indG2use,ind_main)./ml_analyzed_mat_bin(indG2use,ind_main);
  X3 = matdate_bin(ind_highpercent);
  %Y3 = (classcount_bin(ind_highpercent, ind_main)+classcount_bin(ind_highpercent, ind_parasite) +classcount_bin(ind_highpercent, ind_extparas))./ml_analyzed_mat_bin(ind_highpercent,ind_main);
  Y3 =  sum((classcount_bin(ind_highpercent,ind_Gdel)./ml_analyzed_mat_bin(ind_highpercent,ind_Gdel)),2);
  X4 = matdate_bin(indp2use);
  Y4 = classcount_bin(indp2use, ind_parasite)./ml_analyzed_mat_bin(indp2use, ind_parasite);
  Y5 = sum((classcount_bin(indG2use,ind_Gdel)./ml_analyzed_mat_bin(indG2use,ind_Gdel)),2);
  %Y5 = (classcount_bin(indG2use,ind_parasite)+classcount_bin(indG2use,ind_main)+classcount_bin(indG2use,ind_extparas))./ml_analyzed_mat_bin(indG2use,ind_extparas);
  %Y6 = classcount_bin(ind60,ind_extparas)./ml_analyzed_mat_bin(ind60,ind_extparas);
  
  
%  Auto-generated by MATLAB on 17-Jul-2013 10:39:53

% Create figure
figure1 = figure;
set(gcf, 'units', 'inches')
 set(gcf, 'position', [0 0 15 14], 'paperposition', [1 0 15 14], 'color', 'w');

 
 
subplot1 = subplot(4,1,1, 'Parent', figure1,...
    'YTick',[0 .5 1],...
    'YTickLabel',{'0','.5','1'},...
    'Xticklabel', [],...
    'XTick',datenum({'1-1-2007', '1-1-2008', '1-1-2009', '1-1-2010', '1-1-2011', '1-1-2012', '1-1-2013', '1-1-2014', '1-1-2015'}),...
    'FontSize',20, 'ylim', [0 1]);
xlim(subplot1,datelim);
datetick('x', 'keeplimits', 'keepticks')
set(gca, 'xticklabel', [])

box(subplot1,'on');
hold(subplot1,'all');

text(datenum('5-1-2013'), .9, 'a', 'FontSize',23);

lineh = line(repmat(mdate(lowT),1,2), ylim + [.001 -.001]);
set(lineh, 'color', [gray gray gray])
ax = plot(X,Y, 'Parent', subplot1, 'Marker','.','LineWidth',1,'Color',[0 0 1]);

line(repmat(get(gca, 'xtick'),2,1)', ylim, 'linestyle', ':', 'color', 'k')

ylabel({'\itG. delicatula\rm'; 'biomass fraction'},'FontSize',20)
%ylabel({'Infected'; 'chains (ml^{ -1})'},'FontSize',20);

shiftup= -0.032
vertical_stretch =.05

p = get(gca, 'position');
p(2) = p(2);
p(4) = p(4) + vertical_stretch;
set(gca, 'position', p);


% Create axes
%subplot2 = subplot(2,1,1,'Parent',figure1);
subplot2 = subplot(4,1,2, 'Parent', figure1,...
    'YTick',[0 40 80 120],...
    'YTickLabel',{'0','40','80','120'},...
    'Xticklabel', [],...
    'XTick',datenum({'1-1-2007', '1-1-2008', '1-1-2009', '1-1-2010', '1-1-2011', '1-1-2012', '1-1-2013', '1-1-2014', '1-1-2015'}),...
    'FontSize',20, 'ylim', [0 130]);
% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot2,datelim);
% Uncomment the following line to preserve the Y-limits of the axes
%ylim(subplot2,[0 130]);
datetick('x', 'keeplimits', 'keepticks')
%set(gca, 'xticklabel', [])

box(subplot2,'on');
hold(subplot2,'all');

text(datenum('5-1-2013'), 112, 'b', 'FontSize',23);

lineh = line(repmat(mdate(lowT),1,2), ylim + [.01 -.01]);
set(lineh, 'color', [gray gray gray])

ax = plot(X2,Y5, 'Parent', subplot2, 'Marker','.','LineWidth',1,'Color',[0 0 1]);

bx = plot(X3,Y3,'Marker','o','LineStyle','none','Color', [1 0 0], 'MarkerSize',6);

line(repmat(get(gca, 'xtick'),2,1)', ylim, 'linestyle', ':', 'color', 'k')

%an = annotation('rectangle',...
 %   [0.18 0.8 0.05 0.09],...
  %  'FaceColor',[1 1 1],...
   % 'Color',[1 1 1]);

lh = legend([ax, bx], '\itG. delicatula\rm', '> 10% infection', 'location', 'northwest');
set(lh, 'box', 'on', 'edgecolor', [1 1 1], 'FontSize',17)
% Create ylabel
ylabel('Chains (ml^{ -1})','FontSize',20);

%line(xlim, [5 5],'linestyle',  '--', 'color', 'k', 'linewidth', 1.25)


p = get(gca, 'position');
p(2) = p(2)+ shiftup;
p(4) = p(4) + vertical_stretch;
set(gca, 'position', p);
  
%set(lh, 'box', 'on', 'color', 'w')

%************************************

subplot3 = subplot(4,1,3, 'Parent', figure1,...
    'YTick',[0 5 10 15],...
    'YTickLabel',{'0', '5', '10', '15'},...
    'Xticklabel', [],...
    'XTick',datenum({'1-1-2007', '1-1-2008', '1-1-2009', '1-1-2010', '1-1-2011', '1-1-2012', '1-1-2013', '1-1-2014', '1-1-2015'}),...
    'FontSize',20, 'ylim', [0 18]);
% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot3,datelim);
% Uncomment the following line to preserve the Y-limits of the axes
%ylim(subplot3,[0 50]);
datetick('x', 'keeplimits', 'keepticks')
set(gca, 'xticklabel', [])

box(subplot3,'on');
hold(subplot3,'all');

text(datenum('5-1-2013'), 16, 'c', 'FontSize',23);

lineh = line(repmat(mdate(lowT),1,2), ylim + [.1 -.1]);
set(lineh, 'color', [gray gray gray])

%plot(X1,Y1, 'Parent', subplot3, 'Marker','d','LineWidth',1,'MarkerEdgeColor',[1 0 0],...
%                       'MarkerFaceColor',[1 1 1],'Color',[1 0 0], 'MarkerSize',4);
%plot(X1,Y1,'+r-', 'Parent', subplot3, 'MarkerSize',5);
plot(X1(Y1==0),Y1(Y1==0),'+b', 'Parent', subplot3, 'MarkerSize',8);
hold on
plot(X4,Y4, 'dr', 'Parent', subplot3,'markerfacecolor', 'r', 'markersize', 5);
plot(X1,Y1,'r-', 'Parent', subplot3);
%plot(X1,Y6,'.g-', 'Parent', subplot3, 'MarkerSize',4);
%plot(X4,Y4,'Parent', subplot3,'Marker','.','LineStyle','none','LineWidth',1, 'Color',[1 0 0]);

line(repmat(get(gca, 'xtick'),2,1)', ylim, 'linestyle', ':', 'color', 'k')

ylabel({'Infected'; 'chains (ml^{ -1})'},'FontSize',20);


p = get(gca, 'position');
p(2) = p(2)+ 2*shiftup;
p(4) = p(4) + vertical_stretch;
set(gca, 'position', p);


subplot4 = subplot(4,1,4, 'Parent', figure1,...
    'YTick',[0 10 20],...
    'YTickLabel',{'0', '10', '20'},...
    'XTick',datenum({'1-1-2007', '1-1-2008', '1-1-2009', '1-1-2010', '1-1-2011', '1-1-2012', '1-1-2013', '1-1-2014', '1-1-2015'}),...
    'FontSize',20, 'ylim', [-2 23]);
% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot4,datelim);
% Uncomment the following line to preserve the Y-limits of the axes
%ylim(subplot4,[0 50]);
datetick('x', 'keeplimits', 'keepticks')

box(subplot4,'on');
hold(subplot4,'all');

text(datenum('5-1-2013'), 20.5, 'd', 'FontSize',23);

lineh = line(repmat(mdate(lowT),1,2), ylim + [.1 -.1] );
set(lineh, 'color', [gray gray gray])
ax = plot(Tbeam.mdate_mat(:), Tbeam.Tday_beam(:), 'g', 'linewidth', 2);
hold on
bx = plot(mdate(:), Tday(:), 'k');
lh = legend([ax, bx], '4 m', '12 m');
set(lh, 'box', 'on', 'edgecolor', [1 1 1], 'FontSize',15, 'Position',[.19 0.183 0.035 0.016]);



line(xlim, [4 4],'linestyle',  '--', 'color', 'k', 'linewidth', 1.25)
line(repmat(get(gca, 'xtick'),2,1)', ylim, 'linestyle', ':', 'color', 'k')


p = get(gca, 'position');
p(2) = p(2)+3*shiftup;
p(4) = p(4) + vertical_stretch;
set(gca, 'position', p);


ylabel('Temperature (\circC)','FontSize',20);
%tpos = get(lh, 'position');
%tpos(1:2) = [0.1645    0.3597];
%set(lh, 'position', tpos)

% Create ylabel

set(gcf, 'position', [0         0   15.0000   10.2083])


