class2use = {...
    'unknown'...
    'blurry'...
    'marSnow'...
    'phaeIndiv'...
    'phaeMany'...
    'phaeMany23'...
    'squashed'...
    'whiteout'...
    'ribbon'...
    'copepod'...
    'ctenophore'...
    'phaeIndiv2'...
    'phaeManyMix'...
    'phaeManyMix_phae2_primary'...
    'phaeManyMix_squashed_primary'
    };
    
    save class2use_vpr class2use